package ClinicMindhub.Medical.Clinic.models;

public enum MedicalSpeciality {

    CARDIOLOGIST,
    PEDIATRICIAN,
    NEUROLOGIST,
    GASTROENTEROLOGIST,
    PSYCHIATRIST,
    DERMATOLOGIST,
    UROLOGIST,
    ONCOLOGIST,
    ENDOCRINOLOGIST,
    NEPHROLOGIST,
    RHEUMATOLOGIST,
    GYNECOLOGIST,
    PULMONOLOGIST,
    TRAUMATOLOGIST

}
